name: CD

on:
  push: 
    branches:
      - "master"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: npm
      -
        name: Install dependencies
        run: npm install
      -
        name: Run Tests
        run: npm test